### ISSUE TITLE
Bridge backwards too?

### ISSUE THREAD

**Issue by volomike** [yglukhov/cocoa.d#4]
Not really an issue -- a question.

Is there a way my Objective C code can call D functions? Ideally, I'd like to pass strings and integers, or arrays thereof, between the two, backwards and forwards.

Second, is there a way for my D code to call Apple Foundation Class stuff to like show a file dialog?

Note -- I've made an Objective C app with a native OSX webkit widget on it. That gives me a powerful GUI pretty quickly. I then enabled the Javascript bridge so that I can call ObjC stuff from Javascript. But I loathe coding in Obj C -- too much typing and brackets. So, I'd love for my Javascript to call Obj C and then pass right on through to the D code, and I'd love the D code to be powerful enough to call Apple Foundation Class stuff. The D could then return results back to Obj C, which then get passed back in my Obj C code back to the Javascript in the webkit component.

**Comment by yglukhov** [comment]
> Is there a way my Objective C code can call D functions? Ideally, I'd like to pass strings and integers, or arrays thereof, between the two, backwards and forwards.

You can define a D function with C linkage, and then call it from Obj-C. That doesn't even require `cocoa.d`. Also with the help of `cocoa.d` you can define a subclass of Obj-C class. See the sample here:
http://yglukhov.github.io/cocoa.d/cocoa.html

Please note, that I'm not planning to support the lib anymore, as I have moved to Nim =)

**Comment by yglukhov** [comment]
> Second, is there a way for my D code to call Apple Foundation Class stuff to like show a file dialog?

Sure, just see the doc again on how to do that =)
